services:
  app:
    build: .
    env_file: .env
    restart: always
    environment:
      MONGO_HOST: mongo
      TZ: Europe/Moscow
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db
volumes:
  mongo: